Created an error checking section
Created a error checking section to see if the ADB command was successful. If it wasn't, then the variable is empty. If it isn't, then it proceeds with the rest of the script.

diff --git a/android_cfgator b/android_cfgator
--- a/android_cfgator
+++ b/android_cfgator
@@ -22,10 +22,18 @@ SERIAL=$(./adb devices | sed -n '2 p'| sed -e 's/\device//g' | sed -r 's/\s+//g'
 
 # Use that serial number as a parameter to install the .apk's to the phone
 #
-# Install Ampere to measure battery health
-echo "Installing Ampere..."
-./adb -s $SERIAL install com.gombosdev.ampere.apk
 
-#Use PhoneDoctorPlus to run the rest of the tests
-echo "Installing PhoneDoctorPlus..."
-./adb -s $SERIAL install com.idea.PhoneDoctorPlus.apk
+# Check to see if the ADB command was able to sucessfully connect to the phone
+if [[ -z "$SERIAL" ]]
+then
+	echo "An error occurred (did you enable USB debugging on the phone?)"
+	exit 1
+else
+	# Install Ampere to measure battery health
+	echo "Installing Ampere..."
+	./adb -s $SERIAL install com.gombosdev.ampere.apk
+
+	#Use PhoneDoctorPlus to run the rest of the tests
+	echo "Installing PhoneDoctorPlus..."
+	./adb -s $SERIAL install com.idea.PhoneDoctorPlus.apk
+fi
